feat: prod, dev 분리 스크립트 작성

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -66,49 +66,49 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-      - name: Set target IP
-        if: github.ref == 'refs/heads/main'
-        run: |
-          STATUS=$(curl -o /dev/null -w "%{http_code}" "https://hongikyeolgong2.site/env")
-          echo $STATUS
-          if [ $STATUS = 200 ]; then
-            CURRENT_UPSTREAM=$(curl -s "https://hongikyeolgong2.site/env")
-          else
-            CURRENT_UPSTREAM=green
-          fi
-          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
-          if [ $CURRENT_UPSTREAM = blue ]; then
-            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-          elif [ $CURRENT_UPSTREAM = green ]; then
-            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
-          else
-            echo "error"
-            exit 1
-          fi
+#      - name: Set target IP
+#        if: github.ref == 'refs/heads/main'
+#        run: |
+#          STATUS=$(curl -o /dev/null -w "%{http_code}" "https://hongikyeolgong2.site/env")
+#          echo $STATUS
+#          if [ $STATUS = 200 ]; then
+#            CURRENT_UPSTREAM=$(curl -s "https://hongikyeolgong2.site/env")
+#          else
+#            CURRENT_UPSTREAM=green
+#          fi
+#          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+#          if [ $CURRENT_UPSTREAM = blue ]; then
+#            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+#            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+#            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+#          elif [ $CURRENT_UPSTREAM = green ]; then
+#            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+#            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+#            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+#          else
+#            echo "error"
+#            exit 1
+#          fi
 
-      - name: Check deploy server URL (main)
-        if: github.ref == 'refs/heads/main'
-        uses: jtalk/url-health-check-action@v3
-        with:
-          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/env
-          max-attempts: 3
-          retry-delay: 10s
+#      - name: Check deploy server URL (main)
+#        if: github.ref == 'refs/heads/main'
+#        uses: jtalk/url-health-check-action@v3
+#        with:
+#          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/env
+#          max-attempts: 3
+#          retry-delay: 10s
 
-      - name: Stop current server (main)
-        if: github.ref == 'refs/heads/main'
-        uses: appleboy/ssh-action@master
-        with:
-          username: ubuntu
-          host: ${{ secrets.LIVE_SERVER_IP }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
-          script: |
-            sudo docker stop ${{env.CURRENT_UPSTREAM}}
-            sudo docker rm ${{env.CURRENT_UPSTREAM}}
+#      - name: Stop current server (main)
+#        if: github.ref == 'refs/heads/main'
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.LIVE_SERVER_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+#            sudo docker rm ${{env.CURRENT_UPSTREAM}}
 
       - name: Stop current server (develop)
         if: github.ref == 'refs/heads/develop'
@@ -122,17 +122,17 @@ jobs:
             sudo docker stop dev
             sudo docker rm dev
 
-      - name: Docker compose (main)
-        if: github.ref == 'refs/heads/main'
-        uses: appleboy/ssh-action@master
-        with:
-          username: ubuntu
-          host: ${{ secrets.LIVE_SERVER_IP }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
-          script: |
-            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hongik:latest
-            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+#      - name: Docker compose (main)
+#        if: github.ref == 'refs/heads/main'
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.LIVE_SERVER_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hongik:latest
+#            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
 
       - name: Docker compose (develop)
         if: github.ref == 'refs/heads/develop'
@@ -146,16 +146,16 @@ jobs:
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hongik:latest
             sudo docker-compose -f docker-compose.yml up -d
 
-      - name: Change nginx upstream
-        if: github.ref == 'refs/heads/main'
-        uses: appleboy/ssh-action@master
-        with:
-          username: ubuntu
-          host: ${{ secrets.LIVE_SERVER_IP }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
-          script: |
-            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+#      - name: Change nginx upstream
+#        if: github.ref == 'refs/heads/main'
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.LIVE_SERVER_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload'
 
 
 
